# -*- coding: utf-8 -*-
"""GuruSupriya_Peruri_20260321.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZaVZdc6b6f8rARaQPz3lApDUN2ggMMG
"""

'''
(Home  work)
Write  a  program  to  determine  frequency  of  each  vowel  in  the  string  in  alphabetical  order (Ignoring  the  case)

Let  input  be  RamA    raO
What  is  the  output ?  --->  {'A' : 3 , 'O' : 1}

Hint:  Same  as  prog23a  with  minor  changes
'''

a=input('Enter any String').upper()
b={}
for i in a:
  if i in 'AEIOU':
    b[i]=b.get(i,0)+1
print(b)

# Find outputs  (Home  work)
def   f1():
	print('Hyd')
	print('Sec')
	print('Cyb')
# End  of  the  function
print('Begin')
x = f1()
print(x)
print(type(x))
print('End')
'''
Begin
Hyd
Sec
Cyb
None
<class 'Function'>
End
'''

# Find  outputs  (Home  work)
def  f1():
	return   10 , 20 , 30
# End  of  the  function
x = f1()
print(x) #error
print(type(x)) # error
a , b , c =  f1()
print(a) # 10
print(b) # 20
print(c) # 30
print('for  loop')
for  k   in   f1():
	print(k)
'''
10
20
30'''

# Find  outputs
def    f1():
	return  10
	return  20
	return  30
# End  of  the  function
print('Begin') # Begin
x = f1()
print(x) #10
print('End') # 'End'
return   100 # error



#  Find  outputs
f1()   # error
def   f1():
        print('Hello')
print(f1())  # Hello <nextline>  None
print(f1) # Function at xxxx

# Find  outputs  (Home  work)
print('Hello') # Hello
def  f1():
        print('f1  function')
#End  of   function
print('Hi') # Hii
print(f1()) # f1 function <Nextline> None
print(f1)  # Function at xxxx
print('Bye') # Bye

#  Find  outputs
def    f1():
        print('Hyd')
        print('Sec')
        print('Cyb')
#End  of  the  function
print('Begin') # Begin
print(type(f1)) # <class 'Function'>
print(id(f1)) # xxx
print('End') # End

# len()  function  demo  program  (Home  work)
a  =  {'Empno'  :  25,  'Ename'  :  'Rama  Rao'  ,  'Sal'  :  1000.65  }
print(len(a)) # 3
b = {}
print(len(b)) # 0


'''
What  does  len(dict)  do ?  --->  Returns  number  of  key : value  pairs  in  the  dictionary
'''

#  sum()  function demo  program  (Home  work)
a = {10 : 20 , 30 : 40 , 50 : 60}
print(sum(a . keys())) # 90
print(sum(a . values())) # 120
print(sum(a)) # 90
print(sum(a . items())) # error

# max()  and  min()   functions  demo  program  (Home  work)
a = {10 : 20 , 30 : 25 , 40 : 5 , 7 : 28 , 9 : 50}
print(max(a . keys())) # 40
print(min(a . keys())) # 9
print(max(a . values())) # 50
print(min(a . values())) # 5
print(max(a . items())) # (40,5)
print(min(a . items())) # (9,50)
print(max(a)) # 40
print(min(a)) # 9

#  dict()  function  demo program (Home  work))
a = [ (10 , 'Hyd') , (20 , 'Sec') , (15 , 'Cyb') , (20 , 'Pune')]
b = dict(a) #{10:'Hyd',20:'Pune',15:'Cyb' }
print(b)#{10:'Hyd',20:'Pune',15:'Cyb' }
c = ( ['R' , 'Red'] , ['G' , 'Green'] , ['B' , 'Blue'] , ['G' , 'Gray'])
d = dict(c) # {'R':'Red','G':'Gray','B':'Blue'}
print(d) # {'R':'Red','G':'Gray','B':'Blue'}
e = [[10 , 20 , 30] , [40 , 50 , 60] , [70 , 80 , 90]]
print(dict(e)) # error
f = [[10] , [20] , [30]]
print(dict(f)) # error
print(dict([10 , 20])) # error
g = [[10 , [20 , 30]] , [40 , [50 , 60]] , [70 , [80 , 90]]]
print(dict(g)){10:[20 , 30] , 40 : [50 , 60] , 70 :[80 , 90]}
h = [[[10 , 20] , 30] , [[40 , 50] , 60] , [[70 , 80] , 90]]
print(dict(h)) # error
i = [[(10 , 20) , 30] , [(40 , 50) , 60] , [(70 , 80) , 90]]
print(dict(i))  #{(10 , 20):30 , (40 , 50) : 60 , (70 , 80):90}



# sorted()  function  (Home  work)
a = {10 : 'Red' , 20 : 'Green' , 15 : 'Blue' , 18 : 'Yellow' , 5 : 'White'}
b = sorted(a . keys())
print(b)# [5,10,15,18,20]
c = sorted(a . values())
print(c) #['Blue','Green','Red','White','Yellow']
d = sorted(a . items()) #[(5 ,'White') ,(10,'Red'),(15, 'Blue') , (18,'Yellow') ,(20,'Green' )]
print(d)  #[(5 ,'White') ,(10,'Red'),(15, 'Blue') , (18,'Yellow') ,(20,'Green' )]
f  = sorted(a  , reverse = True)
print(f) #[20,18,15,10,5]
print(a) #{10 : 'Red' , 20 : 'Green' , 15 : 'Blue' , 18 : 'Yellow' , 5 : 'White'}

'''
Write  a  program  to  sort  dictionary  wrt  keys  (Home  work)

1) Let  input  be   {10 : 'A' , 20 : 'B' , 15 : 'C' , 5 : 'D' , 12 : 'E'}
    What  is  the  output ?  ---> {5 : 'D' , 10 : 'A' ,  12 : 'E' ,  15 : 'C' , 20 : 'B'}

2) Both  input  and  output  are  dictionaries

3) Hint:  Use  sorted()  function
'''
a=eval(input("Enter Dictionary"))
b=sorted(a)
c={}
for i in b:
  c[i]=a[i]
print(c)

# clear()  method  demo  program (Home  work)
a = {10 : 20 , 30 : 40 , 50 : 60}
print(a) # {10 : 20 , 30 : 40 , 50 : 60}
a . clear()
print(a) #{}
del  a
print(a) # error