# -*- coding: utf-8 -*-
"""Assignment1_Data_Engineer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcjEVB4d3ZJMmLJmL_9NRcJecVfd2Qee

float  object  demo  program
"""

e = 9.62e-2
print(e)

print(9.8.2)
"""
SyntaxError: invalid syntax in print(9.8.2) happens because Python interprets 9.8.2 as an invalid number.
A number can only have one decimal point.
If you intended to print three separate numbers, they should be separated by commas.
"""

print(9,8,2)

e = 9.62e-2
print(e)
print(9,8,2)

a = 10.8
print(a)
print(type(a))
print(id(a))

b = 25.
print(b)
print(type(b))

c = .689
print(c)

d = 3.4E2
print(d)
print(type(d))

"""complex object demo program"""

a = 3 + 4j
print(a)
print(type(a))
print(id(a))
print(a . real)
print(a . imag)
print(type(a . real))
print(type(a . imag))

# Find outputs (Home work)
a = 6j
print(a)
print(type(a))
print(a.real)
print(a.imag)

print(5 + j6)
"""
The error NameError: name 'j6' is not defined means that Python doesn't recognize j6 as a valid imaginary number.
In Python, the imaginary unit j needs to directly follow its numerical coefficient, like 6j, not j6.
"""

#solution is
print(5 + 6j)

print(3 + 4i)
"""
SyntaxError: invalid decimal literal in print(3 + 4i) happens because Python expects the imaginary unit to be denoted by 'j' or 'J', not 'i'.
To fix this, you should write the imaginary part as 4j.
"""

#solution is
print(3 + 4j)

print(4 + j)
"""
NameError: name 'j' is not defined means that Python tried to use 'j' as a variable, but it hasn't been defined.
When working with complex numbers in Python, the imaginary unit 'j' must always have a number in front of it, even if it's 1.
So, you should write '1j' instead of just 'j'.
"""

print(4 + 1j)

""" bool object demo program"""

a = True
print(a)
print(type(a))
print(id(a))

b = False
print(b)
print(type(b))

print(True + True)

print(True + False)

print(False + True)

print(False + False)

print(True + True + True)

print(25 + 10.8 + True)

print(True > False)

print(True)

print(False)

print(true)
"""
NameError: name 'true' is not defined means that 'true' is not recognized as a keyword or variable in Python.
In Python, boolean values are represented by True and False, both starting with a capital letter.
"""

print(false)
"""
NameError: name 'false' is not defined means that 'false' is not recognized as a keyword or variable in Python.
In Python, boolean values are represented by True and False, both starting with a capital letter.

"""

# Find  outputs (Home  work)
a = 0O6247
print(a)
print(type(a))
print(id(a))

b = 0o6247
print(id(b))
print(b)

c = 3239
print(c)
print(id(c))

print(0o9248)
"""
SyntaxError: invalid digit '9' in octal literal means that you are trying to use the digit '9' in an octal number.
Octal numbers (which start with 0o or 0O) can only contain digits from 0 to 7.
If you intended to print the decimal number 9248, you should remove the 0o prefix.
"""

"""Find  outputs  (Home  work)

"""

a = 0XA7B9
print(a)
print(type(a))

b = 0xBEEF
print(b)

print(A7B9)
"""
NameError: name 'A7B9' is not defined means that Python tried to use 'A7B9' as a variable, but it hasn't been defined.
If you meant to print the hexadecimal number, you should prefix it with '0x', like 0XA7B9.
If you meant to print the text 'A7B9', you should put it in quotes, like 'A7B9'.
"""

print('A7B9')

print(0XBEER)
"""
SyntaxError: invalid hexadecimal literal means that you are trying to use an invalid character 'R' in a hexadecimal number.
Hexadecimal numbers (which start with 0x or 0X) can only contain digits from 0-9 and letters A-F.
The current code b = 0xBEEF is correct, and the cell can now be executed.
"""

print(0XHYD)
"""
SyntaxError: invalid hexadecimal literal in print(0XHYD) happens because hexadecimal numbers (which start with 0x or 0X) can only contain digits from 0-9 and letters A-F.
The characters 'H', and 'Y' are not valid hexadecimal digits. To fix this, you should replace them with valid hexadecimal digits (e.g., 0xA7B).
"""

print(0xA7G9B)

"""
SyntaxError: invalid hexadecimal literal in print(0xA7G9B) happens because hexadecimal numbers (which start with 0x or 0X) can only contain digits from 0-9 and letters A-F.
The character 'G' is not a valid hexadecimal digit.
To fix this, you should replace 'G' with a valid hexadecimal digit, for example, 0xA7B9B.
"""

a = 9248
print(a)
print(type(a))