show databases;
create database employeedb;
use employeedb;
create table employees(emp_id int primary key auto_increment,emp_name varchar(50),department varchar(50),salary decimal(10,2),age int,joining_data date);
show index from employees; 
insert into employees values (null,'ssk','hr',45000,30, '2023-01-10');
insert into employees (emp_name,department,salary,age,joining_data) values ('alice','it',60000,28,'2022-05-01'),('bob','finance',52000,35,'2021-03-20'),('david','it',6500,32,'2020-07-18');
select * from employees;
insert into employees (emp_name,department) values ('sam','admin');
insert into employees(emp_name,department,salary,age,joining_data) values(upper('kelvin'),'hr',50000,30,'2024-02-09');
select emp_name,salary from employees;
select department, salary,age,joining_data from employees ;
select count(*) as total_employees,avg(salary) "average_salary", max(salary) as highest_salary, min(salary) as lowest_salary from employees group by department having count(*)>=2;
select * from employees where department = 'it';
select department from employees;
select * from emplyees order by salary desc;
select * from employees limit 5 offset 5;
update employee set salary=70000 where emp_id = 1;
set sql_safe_updates = 0;  #disabilling the safe mode
select * from employees where emp_name = 'ssk';
update employees set salary=190000 ,department = 'Manager' where emp_name = 'ssk';
select * from employees where emp_name = 'ssk';
set sql_safe_updates = 1;
replace into employees(emp_id,emp_name,department,salary,age,joining_date)values(1,'john','HP', 20000,31, '2023-01-10');
select * from employees where salary=70000;
insert into employees (emp_id, emp_name, department, salary) values (5, 'chris', 'Marketing', 55000) on duplicate key update salary= values (salary);
insert into employees (emp_id, emp_name, department, salary) values (15, 'chris', 'marketing', 55000) on duplicate key update salary= 190000;
select * from employees where emp_id = 15; 
select* from employees where salary is null;
select count(*) from employees where salary is not null;
select * from employees where emp_name like 'A%';
select * from employees where emp_name not like 'A_';